import type{PromptItem}from'./prompts';
export const collections=[
{slug:'professional-headshots',title:'Professional Headshot Prompts for LinkedIn',desc:'Identity-safe headshots for executives, founders, agents and modern professionals.',match:(p:PromptItem)=>p.category==='Professional'||p.tags.includes('headshot')},
{slug:'ai-photo-editing',title:'AI Photo Editing Prompts That Preserve Identity',desc:'Background replacement, outfit changes and conservative restoration.',match:(p:PromptItem)=>p.category==='Photo Editing'},
{slug:'ecommerce-product-images',title:'E-commerce Product Image Prompt Set',desc:'Marketplace packshots, lifestyle scenes and virtual try-on.',match:(p:PromptItem)=>p.category==='E-commerce'||p.category==='Product'},
{slug:'creator-content',title:'AI Visual Prompts for Content Creators',desc:'YouTube thumbnails, LinkedIn infographics and high-clarity social content.',match:(p:PromptItem)=>p.category==='Content'||p.tags.includes('social')},
{slug:'real-estate-marketing',title:'AI Prompts for Luxury Real Estate Marketing',desc:'Property visuals, listing campaigns and architectural films.',match:(p:PromptItem)=>['Real Estate','Architecture'].includes(p.category)},
{slug:'video-advertising',title:'AI Video Advertising Prompt Collection',desc:'Production-ready direction for UGC, launches, hospitality and automotive campaigns.',match:(p:PromptItem)=>p.tags.includes('video')||['Automotive','Advertising'].includes(p.category)},
{slug:'marketing-agencies',title:'AI Prompt Systems for Marketing Agencies',desc:'Reusable commercial systems for client campaigns, SaaS launches and brand content.',match:(p:PromptItem)=>['SaaS','Advertising','Product'].includes(p.category)},
{slug:'luxury-branding',title:'Luxury Brand Visual Prompt Collection',desc:'Art direction for fragrance, jewelry, interiors and collectible design.',match:(p:PromptItem)=>['Luxury','Jewelry'].includes(p.category)},
{slug:'hospitality-travel',title:'Hotel and Travel Marketing Prompts',desc:'Editorial destination imagery and cinematic launch films for premium properties.',match:(p:PromptItem)=>p.category==='Hospitality'||p.tags.includes('travel')},
{slug:'product-photography',title:'Commercial Product Photography Prompts',desc:'Packshots, campaign heroes, macro imagery and lifestyle product scenes.',match:(p:PromptItem)=>['Product','E-commerce','Packaging','Jewelry'].includes(p.category)}
];