import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,useNavigate}from'react-router-dom';
import{ArrowRight,ArrowUp,Check,Copy,Menu,Sparkles,X,Image as ImageIcon,Clapperboard,WandSparkles,Upload,Search,BookOpen}from'lucide-react';
import'./styles.css';

type Mode='Text'|'Image'|'Video';
const modelData=[
 ['chatgpt','ChatGPT','OpenAI','Writing, research and everyday work'],['claude','Claude','Anthropic','Long-form thinking and precise analysis'],['gemini','Gemini','Google','Multimodal creation and image editing'],['midjourney','Midjourney','Midjourney','High-style visual generation'],['sora','Sora','OpenAI','Cinematic text-to-video creation'],['veo','Veo','Google DeepMind','Professional video with native audio']];
const tools=[
 {slug:'prompt-optimizer',icon:WandSparkles,title:'Prompt Optimizer',tag:'TEXT',desc:'Turn a rough request into a clear, structured prompt with role, context, constraints and output format.'},
 {slug:'image-to-prompt',icon:ImageIcon,title:'Image to Prompt',tag:'IMAGE',desc:'Reverse-engineer a visual into reusable descriptions for Gemini, Midjourney and Stable Diffusion.'},
 {slug:'video-prompt-builder',icon:Clapperboard,title:'Video Prompt Builder',tag:'VIDEO',desc:'Direct camera, action, lighting, pacing and audio for Veo, Sora, Kling and Runway.'},
 {slug:'gemini-prompt-generator',icon:Sparkles,title:'Gemini Photo Prompts',tag:'TRENDING',desc:'Build precise photo-editing prompts while protecting identity, pose and important visual details.'}];
function buildPrompt(idea:string,mode:Mode){const s=idea.trim()||'A luxury fashion editorial campaign';if(mode==='Image')return`SUBJECT\n${s}\n\nSETTING\nMinimal environment with intentional negative space and a clear visual story.\n\nCOMPOSITION\nEditorial framing, refined balance, strong focal point, natural proportions.\n\nLIGHTING\nSoft directional key light, controlled highlights, rich tonal contrast.\n\nSTYLE\nPremium, timeless, cinematic and photorealistic.\n\nCAMERA\n85mm lens, f/2.8, shallow depth of field, high detail.\n\nCONSTRAINTS\nNo text, no watermark, no distorted anatomy, preserve identity and key details.`;if(mode==='Video')return`CONCEPT\n${s}\n\nOPENING FRAME\nEstablish the subject instantly with a strong, uncluttered composition.\n\nACTION\nNatural purposeful motion with continuity and realistic physics.\n\nCAMERA\nSlow dolly-in, 50mm lens, stable cinematic movement.\n\nLIGHTING\nSoft directional light with controlled contrast.\n\nAUDIO\nSubtle location ambience and synchronized natural sound.\n\nOUTPUT\n8-second cinematic sequence, 16:9, seamless motion, no captions.`;return`ROLE\nAct as a senior strategist and precise execution partner.\n\nGOAL\n${s}\n\nCONTEXT\nPrioritize useful, original and audience-appropriate results.\n\nPROCESS\nClarify critical assumptions, create a plan, then deliver the strongest final version.\n\nCONSTRAINTS\nBe specific, avoid filler, and never invent unsupported facts.\n\nOUTPUT\nStart with the final deliverable, followed by concise rationale and actionable next steps.`}
function Header(){const[m,setM]=useState(false);return<header className="nav"><Link className="brand" to="/">PromptStudio AI<span>•</span></Link><nav className={m?'open':''}><Link to="/products">Products</Link><Link to="/inspiration">Inspiration</Link><Link to="/journal">Journal</Link><Link to="/pricing">Pricing</Link></nav><Link className="try" to="/tools/prompt-optimizer">Try Free <ArrowRight size={17}/></Link><button className="mobile" onClick={()=>setM(!m)}>{m?<X/>:<Menu/>}</button></header>}
function Footer(){return<footer><Link className="brand" to="/">PromptStudio AI<span>•</span></Link><p>Prompt less. Create more.</p><div><Link to="/products">Products</Link><Link to="/models">Models</Link><Link to="/journal">Journal</Link><Link to="/pricing">Pricing</Link><Link to="/privacy-policy">Privacy</Link></div><small>© 2026 PromptStudio AI. Built for creators.</small></footer>}
function Shell({children}:{children:React.ReactNode}){return<><Header/>{children}<Footer/></>}
function PromptBox({compact=false}:{compact?:boolean}){const[idea,setIdea]=useState('');const[mode,setMode]=useState<Mode>('Image');const[out,setOut]=useState('');const[copied,setCopied]=useState(false);const go=()=>setOut(buildPrompt(idea,mode));const copy=async()=>{await navigator.clipboard.writeText(out);setCopied(true);setTimeout(()=>setCopied(false),1200)};return<div className={compact?'generator compact':'generator'}><div className="modeTabs">{(['Text','Image','Video']as Mode[]).map(x=><button className={mode===x?'active':''} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><label>WHAT ARE YOU MAKING?</label><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Describe an image, video or task in plain words…"/><div className="generatorBottom"><span>Structured for <b>{mode==='Text'?'Claude':mode==='Image'?'Gemini':'Veo'}</b></span><button onClick={go}>Generate prompt <ArrowRight size={17}/></button></div>{out&&<div className="result"><div className="resultTop"><span>STRUCTURED PROMPT</span><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy'}</button></div><pre>{out}</pre></div>}</div>}
function Hero(){const nav=useNavigate();const[idea,setIdea]=useState('');const go=()=>nav('/tools/prompt-optimizer',{state:{idea}});return<><section className="hero desktopHero"><div className="heroCopy"><div className="eyebrow"><i/>THE AI CREATIVE STUDIO</div><h1>Prompt <em>less.</em><br/>Create <em>more.</em></h1><p>Design, iterate, and ship AI-powered content<br/>across the world’s best models.</p><div className="quick"><Sparkles size={18}/><input value={idea} onChange={e=>setIdea(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()} placeholder="Describe what you want to create…"/><button onClick={go}><ArrowUp/></button></div></div><div className="portrait"><img src="/editorial-portrait.jpg" alt="Luxury monochrome fashion editorial"/><div className="promptCard"><div className="cardTop"><Sparkles size={14}/> Structured Prompt <b/></div><small>SUBJECT</small><p>High fashion editorial portrait</p><small>SETTING</small><p>Minimal studio, soft light</p><small>STYLE</small><p>Monochrome, cinematic</p><Link to="/tools/image-to-prompt">View prompt <ArrowRight size={13}/></Link></div></div></section><section className="mobileHero"><div className="heroCopy"><div className="eyebrow"><i/>THE AI CREATIVE STUDIO</div><h1>Prompt <em>less.</em><br/>Create <em>more.</em></h1><p>Design and ship better AI-powered content.</p><div className="quick"><Sparkles size={18}/><input value={idea} onChange={e=>setIdea(e.target.value)} placeholder="What do you want to create?"/><button onClick={go}><ArrowUp/></button></div></div><img src="/editorial-portrait.jpg" alt="Luxury monochrome fashion editorial"/><div className="mobilePrompt"><Sparkles size={16}/><div><small>STRUCTURED FOR YOUR MODEL</small><p>Subject · setting · composition · light · camera · constraints</p></div><Link to="/tools/image-to-prompt"><ArrowRight/></Link></div></section></>}
function Home(){return<Shell><Hero/><section className="models"><div><span>ALL IN ONE PLACE</span><h2>One studio.<br/>Every model.</h2></div><div className="modelGrid">{modelData.map(m=><Link className="model" to={'/models/'+m[0]} key={m[0]}><strong>{m[1]}</strong><small>by {m[2]}</small></Link>)}</div><Link to="/models">Explore all models <ArrowRight size={16}/></Link></section><section className="homeTools"><div className="sectionHead"><span>FOUR CREATIVE SYSTEMS</span><h2>Less guessing.<br/>More making.</h2><p>Purpose-built workflows instead of a generic chat box.</p></div><ToolGrid/></section><section className="darkCta"><span>BEGIN WITH AN IDEA</span><h2>Make your next prompt<br/><em>impossible to misunderstand.</em></h2><Link to="/tools/prompt-optimizer">Open the studio <ArrowRight/></Link></section></Shell>}
function ToolGrid(){return<div className="toolGrid">{tools.map(T=><Link to={'/tools/'+T.slug} className="toolTile" key={T.slug}><T.icon/><span>{T.tag}</span><h3>{T.title}</h3><p>{T.desc}</p><b>Open tool <ArrowRight size={15}/></b></Link>)}</div>}
function PageHero({eyebrow,title,intro}:{eyebrow:string,title:string,intro:string}){return<section className="pageHero"><span>{eyebrow}</span><h1>{title}</h1><p>{intro}</p></section>}
function Products(){return<Shell><PageHero eyebrow="PRODUCTS" title="A complete prompt studio." intro="Go from a rough thought to model-ready direction for writing, imagery and motion."/><section className="content"><ToolGrid/><div className="split"><h2>Designed around outcomes,<br/>not complicated settings.</h2><div><p>PromptStudio asks only for the decisions that affect your result. It then translates those decisions into a structured, reusable prompt.</p><ul><li>Model-aware prompt structure</li><li>Creative controls in plain language</li><li>Reusable output with no lock-in</li><li>Fast workflows for beginners and professionals</li></ul></div></div></section></Shell>}
function ToolPage({slug}:{slug:string}){const tool=tools.find(t=>t.slug===slug)||tools[0];return<Shell><PageHero eyebrow={tool.tag+' TOOL'} title={tool.title+'.'} intro={tool.desc}/><section className="toolPage"><PromptBox/><div className="how"><span>HOW IT WORKS</span><h2>From intent to instruction<br/>in three clear steps.</h2><div className="steps"><article><b>01</b><h3>Describe the outcome</h3><p>Start with ordinary language. You do not need prompt-engineering vocabulary.</p></article><article><b>02</b><h3>Choose the medium</h3><p>Select text, image or video so the right production details are included.</p></article><article><b>03</b><h3>Copy and create</h3><p>Use your structured prompt in the model you already prefer.</p></article></div></div><FAQ items={[['Is this tool free?','Yes. The current studio is free to use while we build advanced model integrations.'],['Does it generate the final image or video?','It creates a production-ready prompt. You can copy that prompt into your preferred AI model.'],['Which models are supported?','The structure works with ChatGPT, Claude, Gemini, Midjourney, Sora and Veo.']]}/></section></Shell>}
function Inspiration(){return<Shell><PageHero eyebrow="INSPIRATION" title="Ideas worth making." intro="Explore practical starting points for portraits, product campaigns, social content and cinematic stories."/><section className="content"><div className="inspireGrid">{['Monochrome editorial','Quiet luxury product','Cinematic street portrait','Minimal architecture','Premium UGC advertisement','Indian wedding story'].map((x,i)=><article key={x}><div className={'art art'+i}><span>0{i+1}</span></div><small>{i%2?'VIDEO DIRECTION':'IMAGE PROMPT'}</small><h3>{x}</h3><Link to="/tools/image-to-prompt">Build this prompt →</Link></article>)}</div></section></Shell>}
const posts=[['How to write AI image prompts like an art director','A practical system for subject, composition, light, lens and creative constraints.'],['Why longer prompts are not always better','Clarity beats volume. Learn what to remove before you add more instructions.'],['Directing AI video: camera, continuity and sound','Turn a visual idea into a sequence that video models can execute consistently.'],['Preserving faces during AI photo editing','Use identity constraints and reference instructions without flattening creativity.']];
function Journal(){return<Shell><PageHero eyebrow="JOURNAL" title="The craft of clear direction." intro="Field notes on better prompts, stronger creative systems and useful AI workflows."/><section className="content"><div className="postGrid">{posts.map((p,i)=><article key={p[0]}><span>0{i+1} · GUIDE</span><h2>{p[0]}</h2><p>{p[1]}</p><Link to={'/journal/'+(i+1)}>Read field note <ArrowRight size={16}/></Link></article>)}</div></section></Shell>}
function Article(){return<Shell><PageHero eyebrow="FIELD NOTE · 8 MIN" title="How to write AI image prompts like an art director." intro="A prompt becomes more useful when every sentence makes a visual decision."/><article className="article"><p className="lead">The strongest image prompts do not rely on endless adjectives. They establish a clear subject, a visual hierarchy and a small set of compatible production choices.</p><h2>Begin with the job of the image</h2><p>Before choosing a lens or lighting style, define what the image must communicate. A product hero needs clarity and controlled reflections. An editorial portrait can tolerate ambiguity and stronger visual tension.</p><h2>Build in layers</h2><p>Use a predictable order: subject, setting, composition, lighting, visual style, camera and constraints. This keeps the model’s attention on the decisions that matter and makes the prompt easier to revise.</p><blockquote>Good direction reduces uncertainty without removing creative possibility.</blockquote><h2>Use constraints deliberately</h2><p>Negative instructions are valuable when they protect identity, anatomy, brand details or layout. Avoid giant generic negative-prompt lists; they often introduce noise instead of control.</p><Link className="articleCta" to="/tools/image-to-prompt">Build an image prompt <ArrowRight/></Link></article></Shell>}
function Models(){return<Shell><PageHero eyebrow="SUPPORTED MODELS" title="One idea. The right language." intro="Different models respond to different forms of context. Choose a destination and structure your direction accordingly."/><section className="content"><div className="modelsList">{modelData.map((m,i)=><Link to={'/models/'+m[0]} key={m[0]}><b>0{i+1}</b><h2>{m[1]}</h2><p>{m[3]}</p><ArrowRight/></Link>)}</div></section></Shell>}
function Model({slug}:{slug:string}){const m=modelData.find(x=>x[0]===slug)||modelData[0];return<Shell><PageHero eyebrow={'MODEL GUIDE · '+m[2].toUpperCase()} title={m[1]+'.'} intro={m[3]+'. Learn the prompt structure, best use cases and practical workflow.'}/><section className="content"><div className="split"><h2>What works well<br/>with {m[1]}.</h2><div><p>Start with a concrete outcome and enough context to judge success. Separate important constraints from optional style preferences, and state the required output format explicitly.</p><ul><li>Define the objective before adding detail</li><li>Provide relevant source material and context</li><li>State constraints in clear, testable language</li><li>Request an output format suited to your workflow</li></ul><Link className="blackBtn" to="/tools/prompt-optimizer">Create a {m[1]} prompt <ArrowRight/></Link></div></div><FAQ items={[['Do I need a paid '+m[1]+' account?','PromptStudio creates the prompt independently. Access requirements for the final generation depend on the model provider.'],['Can I use the same prompt in another model?','Yes, but model-specific adjustments can improve consistency and formatting.']]}/></section></Shell>}
function Pricing(){return<Shell><PageHero eyebrow="SIMPLE PRICING" title="Start free. Create freely." intro="Use the essential prompt tools now. Advanced saving, teams and model integrations are coming next."/><section className="content"><div className="priceCards"><article><span>FREE</span><strong>₹0</strong><p>For learning and everyday creation.</p>{['5 structured prompts daily','Text, image and video modes','Instant copy and export'].map(x=><div><Check/>{x}</div>)}<Link to="/tools/prompt-optimizer">Start creating</Link></article><article className="featured"><span>PRO · COMING SOON</span><strong>₹399<small>/mo</small></strong><p>For creators who work with AI every day.</p>{['Higher usage limits','Prompt history and collections','Advanced model profiles','No advertising'].map(x=><div><Check/>{x}</div>)}<button>Join the waitlist</button></article></div></section></Shell>}
function FAQ({items}:{items:string[][]}){return<section className="faq"><span>FREQUENTLY ASKED</span><h2>Questions, clearly answered.</h2>{items.map(x=><details key={x[0]}><summary>{x[0]}<b>+</b></summary><p>{x[1]}</p></details>)}</section>}
function Legal({type}:{type:string}){const privacy=type==='Privacy Policy';return<Shell><PageHero eyebrow="LEGAL" title={type+'.'} intro={'Last updated September 2, 2026.'}/><article className="article legal"><h2>{privacy?'Information we collect':'Using PromptStudio'}</h2><p>{privacy?'We may collect basic analytics, submitted feedback and account information when account features become available. Prompts entered into the current browser-based tool are processed locally and are not intentionally stored by us.':'Use the service lawfully and do not submit content that violates rights, privacy or applicable law. Generated prompts are provided as creative assistance, not professional advice.'}</p><h2>{privacy?'Cookies and advertising':'Availability and accuracy'}</h2><p>{privacy?'We may use essential cookies, privacy-friendly analytics and, after approval, advertising technologies such as Google AdSense. Consent controls will be provided where legally required.':'Features may change as the product develops. You are responsible for reviewing AI outputs and verifying important facts before use.'}</p><h2>Contact</h2><p>Questions can be sent through the contact details that will be published before commercial launch.</p></article></Shell>}
function NotFound(){return<Shell><PageHero eyebrow="404" title="This prompt went off-script." intro="The page you requested does not exist."/><section className="center"><Link className="blackBtn" to="/">Return home <ArrowRight/></Link></section></Shell>}
function App(){return<BrowserRouter><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/tools" element={<Products/>}/>{tools.map(t=><Route key={t.slug} path={'/tools/'+t.slug} element={<ToolPage slug={t.slug}/>}/>)}<Route path="/inspiration" element={<Inspiration/>}/><Route path="/journal" element={<Journal/>}/><Route path="/journal/:id" element={<Article/>}/><Route path="/models" element={<Models/>}/>{modelData.map(m=><Route key={m[0]} path={'/models/'+m[0]} element={<Model slug={m[0]}/>}/>)}<Route path="/pricing" element={<Pricing/>}/><Route path="/privacy-policy" element={<Legal type="Privacy Policy"/>}/><Route path="/terms" element={<Legal type="Terms of Use"/>}/><Route path="*" element={<NotFound/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<App/>);